In [4]:
from financeportfolio.cashflows import cashflow_controller

In [5]:
cf = cashflow_controller.Cashflow('examples/configurations/cashflow_example.yaml')

In [6]:
cf.perform_analysis()

Reading the Cash Flow Dataset(s)
Found duplicates in examples/cashflows/cashflow_example.csv These will be added together.
Applying Categorization

Categorizing Transactions: 100%|██████████| 6911/6911 [01:23<00:00, 82.28it/s]

90.93% of the cash flow dataset has been categorized.
The following keywords have not led to any category matches (threshold is 90.00%). Please consider removing or updating these keywords to keep things compact:
Ibiza (60.00%), Car Rental (70.00%), Walmart (71.00%)
Creating the Excel Template
Done! Find the Excel Template here: examples/Cash Flow Overview.xlsx

You can view the transactions by calling the related DataFrame.

In [5]:
print("Weekly Overview")
display(cf._weekly_overview)

print("Monthly Overview")
display(cf._monthly_overview)

print("Quarterly Overview")
display(cf._quarterly_overview)

print("Yearly Overview")
display(cf._yearly_overview)

Weekly Overview

,Totals,Income,Investing,Charity,Government,Health and Insurance,Housing,Study,Subscriptions,Transactions,Transport,Sports,Shopping,Groceries,Food and Drinks,Holidays,Cultural,"Festivals, Clubs and Concerts",Other
week,,,,,,,,,,,,,,,,,,,
2013-12-30/2014-01-05,-15.58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-15.58,0.0,0.0,0.0,0.0,0.0
2014-01-06/2014-01-12,-10.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-10.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-01-13/2014-01-19,17.51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.35,0.0,0.0,0.0,-10.84,0.0,0.0,0.0,0.0,0.0
2014-01-20/2014-01-26,95.11,105.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.53,-3.68,0.0,0.0,0.0,0.0
2014-02-03/2014-02-09,-45.32,0.0,0.0,0.0,0.0,-4.97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-4.71,-35.64,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-14/2023-08-20,-598.65,-10.54,0.0,0.0,-5.23,0.0,0.0,0.0,-4.98,0.0,-63.7,-4.14,-442.87,-62.05,-5.14,0.0,0.0,0.0,0.0
2023-08-21/2023-08-27,3922.47,4250.91,0.0,0.0,-87.28,0.0,0.0,0.0,-29.33,-2.17,-9.67,-4.01,-20.98,-108.64,-59.13,0.0,-7.23,0.0,0.0
2023-08-28/2023-09-03,-3094.29,-928.98,0.0,-20.13,-30.7,-112.83,-1635.87,0.0,0.0,0.0,-42.33,0.0,-204.68,-45.79,-72.98,0.0,0.0,0.0,0.0
2023-09-04/2023-09-10,-620.67,27.16,0.0,0.0,-3.02,0.0,0.0,0.0,-94.7,0.0,-60.35,0.0,-106.57,-66.13,-150.11,-166.95,0.0,0.0,0.0
2023-09-11/2023-09-17,-19.49,12.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-18.43,0.0,0.0,0.0,-13.26,0.0,0.0,0.0,0.0,0.0

Monthly Overview

,Totals,Income,Investing,Charity,Government,Health and Insurance,Housing,Study,Subscriptions,Transactions,Transport,Sports,Shopping,Groceries,Food and Drinks,Holidays,Cultural,"Festivals, Clubs and Concerts",Other
month,,,,,,,,,,,,,,,,,,,
2014-01,86.99,105.32,0.0,0.0,0.0,0.0,0.0,0.0,-10.05,28.35,0.0,0.0,0.0,-32.95,-3.68,0.0,0.0,0.0,0.0
2014-02,-0.74,97.95,0.0,0.0,0.0,-4.97,0.0,-13.17,-18.86,60.5,0.0,0.0,-51.95,-24.5,-40.59,0.0,0.0,0.0,-5.15
2014-03,84.9,100.76,0.0,0.0,0.0,0.0,0.0,-5.79,-9.81,34.41,0.0,0.0,-12.64,-14.38,-5.48,0.0,0.0,0.0,-2.17
2014-04,-70.71,109.99,0.0,0.0,0.0,-17.04,0.0,-28.81,-29.39,14.07,0.0,0.0,-86.45,-9.81,-38.13,0.0,0.0,0.0,14.86
2014-05,-35.5,107.61,0.0,0.0,0.0,0.0,0.0,-1.51,-10.63,36.05,-25.88,0.0,-10.94,-61.34,-38.9,0.0,0.0,0.0,-29.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05,-11146.28,16657.72,0.0,-50.44,-24247.66,-115.12,-1404.2,0.0,-148.23,828.19,-121.11,-8.97,541.23,-354.96,-1270.97,-124.39,-126.93,-118.54,-1081.9
2023-06,-1232.31,3987.4,-1016.73,0.0,-28.06,-118.08,-1622.98,0.0,-121.59,-248.65,-166.45,0.0,-32.75,-237.57,-416.17,-1055.68,0.0,-176.2,21.2
2023-07,62.11,4208.54,0.0,-20.4,-76.64,-101.25,-1552.41,0.0,-128.98,444.46,-96.68,0.0,-522.05,-501.91,-410.48,-1204.08,-115.91,-27.63,167.53
2023-08,-1263.98,3299.23,0.0,-20.13,-123.21,-119.07,-1678.47,0.0,-121.53,-422.23,-162.63,-126.22,-843.27,-285.53,-675.29,0.0,-39.1,0.0,53.47
2023-09,-2473.44,39.36,0.0,0.0,-3.02,-112.83,-1635.87,0.0,-94.7,-18.43,-102.68,0.0,-106.57,-104.5,-167.25,-166.95,0.0,0.0,0.0

Quarterly Overview

,Totals,Income,Investing,Charity,Government,Health and Insurance,Housing,Study,Subscriptions,Transactions,Transport,Sports,Shopping,Groceries,Food and Drinks,Holidays,Cultural,"Festivals, Clubs and Concerts",Other
quarter,,,,,,,,,,,,,,,,,,,
2014Q1,171.15,304.03,0.0,0.0,0.0,-4.97,0.0,-18.96,-38.72,123.26,0.0,0.0,-64.59,-71.83,-49.75,0.0,0.0,0.0,-7.32
2014Q2,-468.63,308.82,0.0,0.0,0.0,-35.98,0.0,-32.26,-40.02,50.12,-25.88,-9.3,-300.35,-89.34,-77.03,0.0,0.0,-364.12,146.71
2014Q3,241.2,300.15,0.0,0.0,0.0,0.0,0.0,-35.47,-30.86,120.43,-51.82,-54.92,-59.44,-91.51,-81.3,-163.07,0.0,435.79,-46.78
2014Q4,205.74,309.75,0.0,0.0,0.0,-34.46,0.0,-9.01,-21.82,175.31,0.0,-18.69,-225.94,-66.78,-70.2,0.0,0.0,0.0,167.58
2015Q1,-136.89,312.34,0.0,0.0,0.0,0.0,0.0,-25.72,0.0,480.36,-107.28,0.0,-752.72,-6.16,-50.82,0.0,-14.48,0.0,27.59
2015Q2,-16.96,325.64,0.0,0.0,0.0,-36.77,0.0,-20.25,-10.52,71.06,-113.35,0.0,-288.03,-39.28,-42.5,0.0,0.0,0.0,137.04
2015Q3,81.82,311.16,0.0,0.0,-36.17,-17.51,0.0,-16.78,0.0,-20.4,-22.65,-4.51,-141.85,-55.17,-31.66,0.0,0.0,0.0,117.36
2015Q4,861.76,293.46,0.0,0.0,-91.4,-17.31,-1026.65,1171.4,-21.27,47.41,-8.54,0.0,-103.53,-49.15,-93.78,0.0,0.0,0.0,761.12
2016Q1,3.38,906.08,0.0,0.0,0.0,0.0,0.0,-1181.49,-10.85,38.43,0.0,0.0,-33.33,-10.25,24.05,-281.97,0.0,0.0,552.71
2016Q2,713.62,1647.38,0.0,0.0,0.0,0.0,0.0,-495.49,0.0,-53.98,-92.91,0.0,-328.22,-1.17,0.0,0.0,0.0,-28.3,66.31
2016Q3,-802.17,356.41,0.0,0.0,0.0,0.0,554.63,-645.07,0.0,21.55,-16.14,-28.12,-447.48,-67.16,-129.8,0.0,0.0,0.0,-400.99
2016Q4,1391.44,2083.25,0.0,0.0,-39.64,0.0,-36.03,-12.42,-9.76,-17.02,64.57,-18.88,-383.52,-114.54,-34.85,0.0,0.0,0.0,-89.72
2017Q1,912.15,2004.63,0.0,0.0,0.0,-328.19,0.0,-15.02,-10.64,-253.92,0.0,-60.55,-548.7,-46.81,-26.2,0.0,0.0,0.0,197.55
2017Q2,664.17,1085.82,0.0,0.0,0.0,-228.88,0.0,-7.15,-30.27,499.03,0.0,-73.49,-335.17,-12.71,-119.22,-223.19,-16.83,-24.85,151.08
2017Q3,-844.9,1028.19,0.0,0.0,0.0,-240.31,-566.3,-418.28,-39.38,-36.96,-115.49,-56.92,-224.49,-357.97,277.9,-494.93,-16.43,-84.15,500.62
2017Q4,-1084.18,2139.99,0.0,0.0,0.0,-177.36,-829.74,-419.15,-3.66,-156.89,-107.49,-66.75,-1038.52,-263.36,-222.26,-164.88,-19.96,0.0,245.85
2018Q1,-889.4,1793.62,-1.04,0.0,49.1,-536.53,-773.88,-814.21,-88.01,92.73,-4.5,-33.83,-366.32,-306.9,-145.3,-3.92,-1.4,-30.05,281.04
2018Q2,888.53,3918.79,0.0,0.0,0.0,-269.3,-461.96,-398.74,-94.66,-9.52,-87.19,-19.54,-392.76,-209.32,-123.35,0.0,-1.4,0.0,-962.52
2018Q3,-349.16,3980.41,0.0,0.0,-157.85,-244.75,0.0,-472.62,-110.43,5.46,-88.07,64.98,-472.75,-374.63,-417.72,-842.94,-72.59,-49.69,-1095.97
2018Q4,-887.78,3296.89,0.0,0.0,-248.17,-169.8,0.0,-776.71,-127.37,132.6,-125.49,-46.12,-825.44,-318.65,-245.51,-195.83,-5.29,-13.91,-1218.98
2019Q1,747.87,5581.87,0.0,0.0,-40.65,-472.31,0.0,-935.63,-77.6,31.49,-110.87,-32.63,-917.53,-424.66,-346.09,-4.81,-60.8,-68.12,-1373.79
2019Q2,380.38,4383.27,0.0,0.0,-175.66,-370.71,0.0,-490.15,-65.45,0.85,-268.71,-118.69,-371.18,-460.82,-200.57,-24.69,-52.83,-49.33,-1354.95
2019Q3,4005.71,11278.31,0.0,0.0,-71.72,-261.77,0.0,142.93,-72.47,-990.26,-334.33,-63.71,-1548.54,-657.51,-310.69,-613.12,-27.91,-30.61,-2432.89
2019Q4,3620.55,8077.25,0.0,0.0,-23.92,-195.38,0.0,-6.03,-76.71,-105.4,-416.19,-198.39,-855.69,-555.16,-505.05,-59.18,-88.78,-31.45,-1339.37
2020Q1,-1124.15,7178.92,-2721.86,0.0,-168.82,-388.43,0.0,-13.83,-19.22,47.06,-1822.02,-197.24,-393.75,-456.18,-393.3,-531.18,-63.04,0.0,-1181.26
2020Q2,7186.58,12039.45,1.0,0.0,184.15,-274.58,0.0,0.0,-43.03,-1.97,-93.39,-134.7,-2171.74,-655.56,-159.46,-111.0,0.0,0.0,-1392.59
2020Q3,-283.27,6927.9,-2817.39,0.0,-11.75,-274.04,0.0,0.0,-19.66,-225.25,-185.57,0.0,-749.8,-706.7,-736.91,6.96,0.0,0.0,-1491.06
2020Q4,-6949.38,7923.06,-2892.59,-250.08,-63.28,-176.54,0.0,0.0,59.04,-66.79,-7772.42,0.0,-1427.87,-555.3,-199.74,0.0,-0.76,0.0,-1526.11
2021Q1,535.49,7605.49,-3026.78,-63.04,-42.86,-39.02,0.0,0.0,-11.3,-73.72,-433.12,0.0,-762.96,-929.0,-482.12,250.3,-2.74,0.0,-1453.64
2021Q2,2415.96,9860.8,-3191.69,-62.88,-67.67,-39.71,0.0,0.0,-53.76,-476.16,-458.07,0.0,-578.86,-904.53,-362.16,141.6,-26.21,0.0,-1364.74
2021Q3,-708.84,7595.79,-3098.0,-85.83,1131.49,-23.2,-52.87,-22.36,-10.52,-439.17,607.71,-30.12,-1781.91,-758.74,-720.85,-1140.0,-67.46,0.0,-1812.8
2021Q4,111.46,9310.45,-2914.78,-62.12,-132.93,-42.32,0.0,-47.66,-134.78,-209.15,-900.67,0.0,-1021.58,-937.51,-1193.24,0.0,-62.76,0.0,-1539.49
2022Q1,4609.13,20340.85,-5571.73,-87.52,-110.75,-369.93,-48.57,0.0,-130.23,12.97,-356.86,-12.88,-5291.96,-732.86,-1145.4,-472.15,-92.04,-42.58,-1279.23
2022Q2,8019.37,23682.8,-8168.7,-59.32,-203.8,-320.34,0.0,0.0,-76.97,47.86,-786.16,-13.29,-1352.57,-793.71,-674.06,-1506.7,-99.15,-32.94,-1623.58
2022Q3,1833.96,24561.19,-5186.74,-63.21,-364.11,-304.85,-3603.15,-2.74,-288.6,-292.52,-407.23,-61.59,-5612.71,-1132.19,-2802.39,-1256.87,-68.81,0.0,-1279.52
2022Q4,5339.81,25242.46,-6079.84,-64.22,-134.12,-344.29,-4459.13,0.0,-289.48,-1911.27,-1541.83,0.0,-2727.33,-1012.04,-1969.67,-421.49,-99.38,0.0,1151.44
2023Q1,12044.12,23684.03,0.0,-60.68,-144.27,-331.27,-4433.81,0.0,-868.65,407.86,-891.06,-444.09,-1028.81,-1058.67,-1998.75,-656.51,-72.84,-138.41,80.05
2023Q2,-17365.97,29037.07,-1016.73,-79.36,-24199.61,-336.79,-4585.64,-8370.02,-388.0,377.59,-571.83,-39.23,114.68,-968.46,-2501.96,-2240.81,-248.61,-314.91,-1033.35
2023Q3,-3675.31,7547.13,0.0,-40.53,-202.87,-333.15,-4866.75,0.0,-345.21,3.8,-361.99,-126.22,-1471.89,-891.94,-1253.02,-1371.03,-155.01,-27.63,221.0

Yearly Overview

,Totals,Income,Investing,Charity,Government,Health and Insurance,Housing,Study,Subscriptions,Transactions,Transport,Sports,Shopping,Groceries,Food and Drinks,Holidays,Cultural,"Festivals, Clubs and Concerts",Other
year,,,,,,,,,,,,,,,,,,,
2014,149.46,1222.75,0.0,0.0,0.0,-75.41,0.0,-95.7,-131.42,469.12,-77.7,-82.91,-650.32,-319.46,-278.28,-163.07,0.0,71.67,260.19
2015,789.73,1242.6,0.0,0.0,-127.57,-71.59,-1026.65,1108.65,-31.79,578.43,-251.82,-4.51,-1286.13,-149.76,-218.76,0.0,-14.48,0.0,1043.11
2016,1306.27,4993.12,0.0,0.0,-39.64,0.0,518.6,-2334.47,-20.61,-11.02,-44.48,-47.0,-1192.55,-193.12,-140.6,-281.97,0.0,-28.3,128.31
2017,-352.76,6258.63,0.0,0.0,0.0,-974.74,-1396.04,-859.6,-83.95,51.26,-222.98,-257.71,-2146.88,-680.85,-89.78,-883.0,-53.22,-109.0,1095.1
2018,-1237.81,12989.71,-1.04,0.0,-356.92,-1220.38,-1235.84,-2462.28,-420.47,221.27,-305.25,-34.51,-2057.27,-1209.5,-931.88,-1042.69,-80.68,-93.65,-2996.43
2019,8754.51,29320.7,0.0,0.0,-311.95,-1300.17,0.0,-1288.88,-292.23,-1063.32,-1130.1,-413.42,-3692.94,-2098.15,-1362.4,-701.8,-230.32,-179.51,-6501.0
2020,-1170.22,34069.33,-8430.84,-250.08,-59.7,-1113.59,0.0,-13.83,-22.87,-246.95,-9873.4,-331.94,-4743.16,-2373.74,-1489.41,-635.22,-63.8,0.0,-5591.02
2021,2354.07,34372.53,-12231.25,-273.87,888.03,-144.25,-52.87,-70.02,-210.36,-1198.2,-1184.15,-30.12,-4145.31,-3529.78,-2758.37,-748.1,-159.17,0.0,-6170.67
2022,19802.27,93827.3,-25007.01,-274.27,-812.78,-1339.41,-8110.85,-2.74,-785.28,-2142.96,-3092.08,-87.76,-14984.57,-3670.8,-6591.52,-3657.21,-359.38,-75.52,-3030.89
2023,-8997.16,60268.23,-1016.73,-180.57,-24546.75,-1001.21,-13886.2,-8370.02,-1601.86,789.25,-1824.88,-609.54,-2386.02,-2919.07,-5753.73,-4268.35,-476.46,-480.95,-732.3

Next to that, you can view all related period datasets that are categorized per week, month, quarter and year.

In [6]:
print("Weekly Cash Flows")
display(cf._weekly_cash_flow_dataset)

print("Monthly Cash Flows")
display(cf._monthly_cash_flow_dataset)

print("Quarterly Cash Flows")
display(cf._quarterly_cash_flow_dataset)

print("Yearly Cash Flows")
display(cf._yearly_cash_flow_dataset)

Weekly Cash Flows

                                                                           name  \
week                  date
2013-12-30/2014-01-05 2014-01-02   toprekening - Omitted due to Privacy Reasons
                      2014-01-02   toprekening - Omitted due to Privacy Reasons
                      2014-01-03         C1000 - Omitted due to Privacy Reasons
                      2014-01-03         C1000 - Omitted due to Privacy Reasons
2014-01-06/2014-01-12 2014-01-06      Vodafone - Omitted due to Privacy Reasons
...                                                                         ...
2023-09-04/2023-09-10 2023-09-10          Tinq - Omitted due to Privacy Reasons
                      2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons
2023-09-11/2023-09-17 2023-09-12  Albert Heijn - Omitted due to Privacy Reasons
                      2023-09-12      geldmaat - Omitted due to Privacy Reasons
                      2023-09-13           asr - Omitted due to Privacy Reasons

                                  value  \
week                  date
2013-12-30/2014-01-05 2014-01-02 -54.08
                      2014-01-02  40.07
                      2014-01-03  -2.33
                      2014-01-03 -13.25
2014-01-06/2014-01-12 2014-01-06 -10.05
...                                 ...
2023-09-04/2023-09-10 2023-09-10 -53.81
                      2023-09-10 -31.63
2023-09-11/2023-09-17 2023-09-12 -13.26
                      2023-09-12 -18.43
                      2023-09-13  12.20

                                                                    description  \
week                  date
2013-12-30/2014-01-05 2014-01-02   toprekening - Omitted due to Privacy Reasons
                      2014-01-02   toprekening - Omitted due to Privacy Reasons
                      2014-01-03         C1000 - Omitted due to Privacy Reasons
                      2014-01-03         C1000 - Omitted due to Privacy Reasons
2014-01-06/2014-01-12 2014-01-06      Vodafone - Omitted due to Privacy Reasons
...                                                                         ...
2023-09-04/2023-09-10 2023-09-10          Tinq - Omitted due to Privacy Reasons
                      2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons
2023-09-11/2023-09-17 2023-09-12  Albert Heijn - Omitted due to Privacy Reasons
                      2023-09-12      geldmaat - Omitted due to Privacy Reasons
                      2023-09-13           asr - Omitted due to Privacy Reasons

                                         category       keyword  certainty
week                  date
2013-12-30/2014-01-05 2014-01-02       Exclusions   toprekening        1.0
                      2014-01-02       Exclusions   toprekening        1.0
                      2014-01-03        Groceries         C1000        1.0
                      2014-01-03        Groceries         C1000        1.0
2014-01-06/2014-01-12 2014-01-06    Subscriptions      Vodafone        1.0
...                                           ...           ...        ...
2023-09-04/2023-09-10 2023-09-10        Transport          Tinq        1.0
                      2023-09-10  Food and Drinks  JOOP SCHOORL        1.0
2023-09-11/2023-09-17 2023-09-12        Groceries  Albert Heijn        1.0
                      2023-09-12     Transactions      geldmaat        1.0
                      2023-09-13           Income           asr        1.0

[6911 rows x 6 columns]

Monthly Cash Flows

                                                             name  value  \
month   date
2014-01 2014-01-02   toprekening - Omitted due to Privacy Reasons -54.08
        2014-01-02   toprekening - Omitted due to Privacy Reasons  40.07
        2014-01-03         C1000 - Omitted due to Privacy Reasons  -2.33
        2014-01-03         C1000 - Omitted due to Privacy Reasons -13.25
        2014-01-06      Vodafone - Omitted due to Privacy Reasons -10.05
...                                                           ...    ...
2023-09 2023-09-10          Tinq - Omitted due to Privacy Reasons -53.81
        2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons -31.63
        2023-09-12  Albert Heijn - Omitted due to Privacy Reasons -13.26
        2023-09-12      geldmaat - Omitted due to Privacy Reasons -18.43
        2023-09-13           asr - Omitted due to Privacy Reasons  12.20

                                                      description  \
month   date
2014-01 2014-01-02   toprekening - Omitted due to Privacy Reasons
        2014-01-02   toprekening - Omitted due to Privacy Reasons
        2014-01-03         C1000 - Omitted due to Privacy Reasons
        2014-01-03         C1000 - Omitted due to Privacy Reasons
        2014-01-06      Vodafone - Omitted due to Privacy Reasons
...                                                           ...
2023-09 2023-09-10          Tinq - Omitted due to Privacy Reasons
        2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons
        2023-09-12  Albert Heijn - Omitted due to Privacy Reasons
        2023-09-12      geldmaat - Omitted due to Privacy Reasons
        2023-09-13           asr - Omitted due to Privacy Reasons

                           category       keyword  certainty
month   date
2014-01 2014-01-02       Exclusions   toprekening        1.0
        2014-01-02       Exclusions   toprekening        1.0
        2014-01-03        Groceries         C1000        1.0
        2014-01-03        Groceries         C1000        1.0
        2014-01-06    Subscriptions      Vodafone        1.0
...                             ...           ...        ...
2023-09 2023-09-10        Transport          Tinq        1.0
        2023-09-10  Food and Drinks  JOOP SCHOORL        1.0
        2023-09-12        Groceries  Albert Heijn        1.0
        2023-09-12     Transactions      geldmaat        1.0
        2023-09-13           Income           asr        1.0

[6911 rows x 6 columns]

Quarterly Cash Flows

                                                             name  value  \
quarter date
2014Q1  2014-01-02   toprekening - Omitted due to Privacy Reasons -54.08
        2014-01-02   toprekening - Omitted due to Privacy Reasons  40.07
        2014-01-03         C1000 - Omitted due to Privacy Reasons  -2.33
        2014-01-03         C1000 - Omitted due to Privacy Reasons -13.25
        2014-01-06      Vodafone - Omitted due to Privacy Reasons -10.05
...                                                           ...    ...
2023Q3  2023-09-10          Tinq - Omitted due to Privacy Reasons -53.81
        2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons -31.63
        2023-09-12  Albert Heijn - Omitted due to Privacy Reasons -13.26
        2023-09-12      geldmaat - Omitted due to Privacy Reasons -18.43
        2023-09-13           asr - Omitted due to Privacy Reasons  12.20

                                                      description  \
quarter date
2014Q1  2014-01-02   toprekening - Omitted due to Privacy Reasons
        2014-01-02   toprekening - Omitted due to Privacy Reasons
        2014-01-03         C1000 - Omitted due to Privacy Reasons
        2014-01-03         C1000 - Omitted due to Privacy Reasons
        2014-01-06      Vodafone - Omitted due to Privacy Reasons
...                                                           ...
2023Q3  2023-09-10          Tinq - Omitted due to Privacy Reasons
        2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons
        2023-09-12  Albert Heijn - Omitted due to Privacy Reasons
        2023-09-12      geldmaat - Omitted due to Privacy Reasons
        2023-09-13           asr - Omitted due to Privacy Reasons

                           category       keyword  certainty
quarter date
2014Q1  2014-01-02       Exclusions   toprekening        1.0
        2014-01-02       Exclusions   toprekening        1.0
        2014-01-03        Groceries         C1000        1.0
        2014-01-03        Groceries         C1000        1.0
        2014-01-06    Subscriptions      Vodafone        1.0
...                             ...           ...        ...
2023Q3  2023-09-10        Transport          Tinq        1.0
        2023-09-10  Food and Drinks  JOOP SCHOORL        1.0
        2023-09-12        Groceries  Albert Heijn        1.0
        2023-09-12     Transactions      geldmaat        1.0
        2023-09-13           Income           asr        1.0

[6911 rows x 6 columns]

Yearly Cash Flows

                                                          name  value  \
year date
2014 2014-01-02   toprekening - Omitted due to Privacy Reasons -54.08
     2014-01-02   toprekening - Omitted due to Privacy Reasons  40.07
     2014-01-03         C1000 - Omitted due to Privacy Reasons  -2.33
     2014-01-03         C1000 - Omitted due to Privacy Reasons -13.25
     2014-01-06      Vodafone - Omitted due to Privacy Reasons -10.05
...                                                        ...    ...
2023 2023-09-10          Tinq - Omitted due to Privacy Reasons -53.81
     2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons -31.63
     2023-09-12  Albert Heijn - Omitted due to Privacy Reasons -13.26
     2023-09-12      geldmaat - Omitted due to Privacy Reasons -18.43
     2023-09-13           asr - Omitted due to Privacy Reasons  12.20

                                                   description  \
year date
2014 2014-01-02   toprekening - Omitted due to Privacy Reasons
     2014-01-02   toprekening - Omitted due to Privacy Reasons
     2014-01-03         C1000 - Omitted due to Privacy Reasons
     2014-01-03         C1000 - Omitted due to Privacy Reasons
     2014-01-06      Vodafone - Omitted due to Privacy Reasons
...                                                        ...
2023 2023-09-10          Tinq - Omitted due to Privacy Reasons
     2023-09-10  JOOP SCHOORL - Omitted due to Privacy Reasons
     2023-09-12  Albert Heijn - Omitted due to Privacy Reasons
     2023-09-12      geldmaat - Omitted due to Privacy Reasons
     2023-09-13           asr - Omitted due to Privacy Reasons

                        category       keyword  certainty
year date
2014 2014-01-02       Exclusions   toprekening        1.0
     2014-01-02       Exclusions   toprekening        1.0
     2014-01-03        Groceries         C1000        1.0
     2014-01-03        Groceries         C1000        1.0
     2014-01-06    Subscriptions      Vodafone        1.0
...                          ...           ...        ...
2023 2023-09-10        Transport          Tinq        1.0
     2023-09-10  Food and Drinks  JOOP SCHOORL        1.0
     2023-09-12        Groceries  Albert Heijn        1.0
     2023-09-12     Transactions      geldmaat        1.0
     2023-09-13           Income           asr        1.0

[6911 rows x 6 columns]